### ISSUE TITLE
Cannot install Scales

### ISSUE THREAD

**Issue by Blackbird1604** [PufferPanel/Scales#10]
Hi i cannot do npm install it throws an error
## npm WARN package.json trim@0.0.1 No repository field.

> userid@0.1.2 install /srv/scales/node_modules/userid
> node-gyp rebuild

make: Entering directory `/srv/scales/node_modules/userid/build'
  CXX(target) Release/obj.target/userid/src/userid.o
make: g++: Command not found
make: *** [Release/obj.target/userid/src/userid.o] Error 127
make: Leaving directory`/srv/scales/node_modules/userid/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab103.6
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/scales/node_modules/userid
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> usage@0.6.0 install /srv/scales/node_modules/usage
> node-gyp rebuild

make: Entering directory `/srv/scales/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
make: g++: Command not found
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 127
make: Leaving directory`/srv/scales/node_modules/usage/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab103.6
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/scales/node_modules/usage
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> pty.js@0.2.7-1 install /srv/scales/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/srv/scales/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory`/srv/scales/node_modules/pty.js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab103.6
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/scales/node_modules/pty.js
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-042stab103.6
npm ERR! argv "/root/.nvm/versions/node/v0.12.2/bin/node" "/root/.nvm/versions/node/v0.12.2/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! userid@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the userid@0.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the userid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls userid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/scales/npm-debug.log

**Comment by LordRalex** [comment]
You do not have g++ installed on your system: make: g++: Command not found

**Comment by Blackbird1604** [comment]
Thank you . It worked for me. Maybe you can add this to the Documentation.
