### ISSUE TITLE
Server just stops!

### ISSUE THREAD

**Issue by DDynamic** [PufferPanel/Scales#12]
Hello,
If I power on a server, it goes through the startup, enables plugins, etc. Then it tells me the server has started successfully. **Shown below:**

```
[16:51:29 INFO]: Done (2.514s)! For help, type "help" or "?"
[16:51:29 INFO]: Starting GS4 status listener
[16:51:29 INFO]: Query running on 167.114.159.112:25566
```

A few seconds later, I receive this message and the server goes offline. **Show below:**

```
[16:51:30 INFO]: Stopping server
```

My Scales verbose logs can be found at https://gist.github.com/Dylan3304/14dc5ac2e153a4ccf387.

**Comment by DaneEveritt** [comment]
Yeah, I see the problem occurring here, the command is checking if the program is listening on un-assigned ports, which it isn't, but its doing a DNS lookup on the IP which is breaking the check.
