### ISSUE TITLE
Scales start error

### ISSUE THREAD

**Issue by Thunderbird2** [PufferPanel/Scales#15]
Hello I get this error when starting scales:

[23:27:49][ERROR] + =========================================== +
[23:27:49][ERROR] |    WARNING: UNHANDLED EXCEPTION DETECTED    |
[23:27:49][ERROR] + =========================================== +
[23:27:49][ERROR] | An unhandled exception occured while trying |
[23:27:49][ERROR] |  to start Scales.js, please report this to  |
[23:27:49][ERROR] |    us and include the log file generated.   |
[23:27:49][ERROR] + =========================================== +
[23:27:49][ERROR] Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Server.listen (net.js:1257:5)
    at Server.listen (/srv/scales/node_modules/restify/lib/server.js:314:32)
    at Object.<anonymous> (/srv/scales/lib/interfaces/restify.js:375:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
[23:27:49][WARN] If this error mentions 'listen EADDRINUSE' please check to ensure that the defined ports for Scales are free (default 5656 - 5658).

**Comment by DaneEveritt** [comment]
`[23:27:49][ERROR] Error: listen EADDRINUSE`

`[23:27:49][WARN] If this error mentions 'listen EADDRINUSE' please check to ensure that the defined ports for Scales are free (default 5656 - 5658).`

You have another Scales instance still running on the server, please take the time to read the messages.

**Comment by Thunderbird2** [comment]
It still displays the same message also I have checked that the ports are open.

**Comment by DaneEveritt** [comment]
Except the ports are not open, because it says they aren't in the error message.

You can just do `npm stop` inside the Scales directory, or run the commands below.

`ps aux | grep node`
`kill -9 PID`

**Comment by Thunderbird2** [comment]
I have tried the above a number of times. Here is what UFW is saying about the ports:

To                         Action      From

---

5656:5658/tcp              ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere
21/tcp                     ALLOW IN    Anywhere
5656:5658/tcp              ALLOW IN    Anywhere (v6)
80/tcp                     ALLOW IN    Anywhere (v6)
21/tcp                     ALLOW IN    Anywhere (v6)

**Comment by DaneEveritt** [comment]
That is not the problem, you still have a Scales instance running somewhere on your server, please read what I wrote above for how to fix it.

UFW is not the problem here.

**Comment by Thunderbird2** [comment]
I have tried both npm stop and
 ps aux | grep node
kill -9 PID  (it says there was no processes found)
but the problem is still occurring. Also I have restarted my machine several times.

**Comment by DaneEveritt** [comment]
What is the output of `ps aux | grep node` and/or `ps aux | grep nodejs`.

**Comment by Thunderbird2** [comment]
Here is the output: 
![image](https://cloud.githubusercontent.com/assets/9033887/7453465/5724b72e-f261-11e4-925c-6ef4c19f1277.png)

**Comment by jaredtbates** [comment]
Try running `killall node` and `killall nodejs`

**Comment by Thunderbird2** [comment]
I have done many a times: 
![image](https://cloud.githubusercontent.com/assets/9033887/7453584/b506a838-f262-11e4-9395-3af8dcc3fff3.png)

![image](https://cloud.githubusercontent.com/assets/9033887/7453592/bf8eda6e-f262-11e4-8ebe-66b132514276.png)

**Comment by jaredtbates** [comment]
Hmmm... I assume that you cannot simply reboot the node?

**Comment by jaredtbates** [comment]
And try `killall npm` but I doubt it will work.

**Comment by Thunderbird2** [comment]
I have tried doing that several times but it seems that nodejs starts on boot. Should I disable this?

**Comment by Thunderbird2** [comment]
No process found again.

**Comment by jaredtbates** [comment]
I don't know... if you can disable it starting at boot, then that probably would fix it.

**Comment by Thunderbird2** [comment]
I re installed nodejs and now upon doing npm start I get this:
![image](https://cloud.githubusercontent.com/assets/9033887/7453943/6d37a328-f266-11e4-9db7-36016fc0ff0f.png)

I then go into the panel and try and create a server but I get this error: "An error occured while trying to connect to the remote node. Please check that Scales is running and try again. "

**Comment by DaneEveritt** [comment]
```
cd /srv/scales
sudo npm stop
```

Then follow [this link](http://www.cyberciti.biz/faq/kill-process-in-linux-or-terminate-a-process-in-unix-or-linux-systems/) for how to kill a rogue process, you'll want to kill `node` and `nodejs`. There is no reason why Scales would auto-boot at startup, so if you've actually been restarting your entire VPS and this is still persisting then there is an issue elsewhere in the system.

When Scales starts it will look like your picture above, that is completely normal.

**Comment by Thunderbird2** [comment]
Ah silly me, it was because my SSL certificate was invalid.
