### ISSUE TITLE
Zombie Process'

### ISSUE THREAD

**Issue by DaneEveritt** [PufferPanel/Scales#22]
It appears that there is a bug with `pty.js` (see [here](https://github.com/chjj/pty.js/issues/37) and [here](https://github.com/chjj/pty.js/issues/58)) which prevents stopped processes from actually closing out correctly, so they become zombies to the `scales.js` process.

Not sure how we will go about fixing this, but at this point it doesn't look like there is too much we can do unfortunately. It was suggested to use `waitpid()`, however that doesn't seem to be compatible with NodeJS `0.12`, unless that was just a bug on my system.

To reproduce this, simply start a server and then stop it. You can do this over and over, and then run `ps aux | grep <process>` (i.e. `java`) and you will see a long list of zombie processes form over time.

**Comment by DDynamic** [comment]
@LordRalex do you think you'll be able to fix this? Or will we have to wait for @DaneEveritt to return? This is a pretty big issue.

**Comment by LordRalex** [comment]
@BlameDylan I have 0 knowledge of nodejs or Scales. I can BS a fix if I spend time on it, but at this point, that time is hard to get. I'd rather have someone help patch it and submit a PR, since that requires less time for me to allocate.

**Comment by DDynamic** [comment]
I'm currently learn NodeJS. Maybe I can do something.

**Comment by Mstrodl** [comment]
Is there any sort of work-around for this? Is it as simple as restarting Scales?

**Comment by aadeg** [comment]
It will be fixed soon?

**Comment by DDynamic** [comment]
@aadeg I think it has been fixed in the "zombies" branch.

**Comment by aadeg** [comment]
@BlameDylan The last commit was 1 month ago... I hope it will be fixed.

**Comment by Mstrodl** [comment]
@aadeg The commit message says

> Attempt to fix zombie processes

**Comment by DaneEveritt** [comment]
You can fix the Zombie Process issue by just restarting Scales for now. There is nothing we can do until it is fixed in an upstream dependency branch.

**Comment by LordRalex** [comment]
pty.js has made some updates and it appears those update may fix this issue. If this issue continues using the latest Scales release, please comment on this issue.

**Comment by DaneEveritt** [comment]
Make sure to `npm update` after applying the change.

**Comment by LordRalex** [comment]
With 0.1.4 released, and the fix in theory applied, I am closing this. Should pty.js fix it in the future on the 0.2.x builds, npm update will apply it.
