### ISSUE TITLE
Server.cfg not being generated

### ISSUE THREAD

**Issue by ajarmoszuk** [PufferPanel/Scales#25]
When creating a new SRCDS server which requires a server.cfg file to run properly, ie assign commands such as server title, gamemode, map etc does not get created at all, I'm not sure if this function is to be added eventually, but it's a vital function and should be added ASAP.

**Comment by Chemox** [comment]
This file gets created as "server.cfg.example"
You can create the file manually by clicking the "+" behind the path inside the files manager.
Though adding a file renaming function for text files which uses the 'file' command to determine if the filetype is a text file (linux isn't made for using extensions anyway...) and not some executable would be more convenient.
