### ISSUE TITLE
Scales - Centos kernel panic

### ISSUE THREAD

**Issue by Foorack** [PufferPanel/Scales#26]
This causes scales and pufferpanel to crash completely... I have no idea why. It happens at random

Jun 27 20:07:45 ******\* kernel: INFO: task java:19740 blocked for more than 120 seconds.
Jun 27 20:07:45 ******\* kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun 27 20:07:45 ******\* kernel: java            D ffff88081fdd3680     0 19740   3536 0x00000080
Jun 27 20:07:45 ******\* kernel: ffff88071eaab9c0 0000000000000082 ffff88071eaabfd8 0000000000013680
Jun 27 20:07:45 ******\* kernel: ffff88071eaabfd8 0000000000013680 ffff880036be4fa0 ffff8807f33633b0
Jun 27 20:07:45 ******\* kernel: 7fffffffffffffff ffff880036be4fa0 0000000000000002 0000000000000000
Jun 27 20:07:45 ******\* kernel: Call Trace:
Jun 27 20:07:45 ******\* kernel: [<ffffffff8160a1d9>] schedule+0x29/0x70
Jun 27 20:07:45 ******\* kernel: [<ffffffff81608119>] schedule_timeout+0x209/0x2d0
Jun 27 20:07:45 ******\* kernel: [<ffffffff816096b2>] __down_common+0xd2/0x14a
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01bc2dd>] ? _xfs_buf_find+0x16d/0x2c0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffff81609747>] __down+0x1d/0x1f
Jun 27 20:07:45 ******\* kernel: [<ffffffff8109d311>] down+0x41/0x50
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01bc0dc>] xfs_buf_lock+0x3c/0xd0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01bc2dd>] _xfs_buf_find+0x16d/0x2c0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01bc45a>] xfs_buf_get_map+0x2a/0x180 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01d5b77>] ? kmem_zone_alloc+0x77/0x100 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01bceec>] xfs_buf_read_map+0x2c/0x140 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa0220809>] xfs_trans_read_buf_map+0x2d9/0x4a0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa020e05e>] xfs_imap_to_bp+0x6e/0xf0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa0206e95>] xfs_iunlink_remove+0x295/0x3b0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa020a1df>] xfs_ifree+0x2f/0xf0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa020a338>] xfs_inactive_ifree+0x98/0x1d0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffff811f0520>] ? __inode_wait_for_writeback+0x80/0xf0
Jun 27 20:07:45 ******\* kernel: [<ffffffffa020a51a>] xfs_inactive+0xaa/0x160 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffffa01d10be>] xfs_fs_evict_inode+0x7e/0xc0 [xfs]
Jun 27 20:07:45 ******\* kernel: [<ffffffff811e23d7>] evict+0xa7/0x170
Jun 27 20:07:45 ******\* kernel: [<ffffffff811e2c15>] iput+0xf5/0x180
Jun 27 20:07:45 ******\* kernel: [<ffffffff811d77ce>] do_unlinkat+0x1ae/0x2b0
Jun 27 20:07:45 ******\* kernel: [<ffffffff816105ca>] ? do_page_fault+0x1a/0x70
Jun 27 20:07:45 ******\* kernel: [<ffffffff811d87d6>] SyS_unlink+0x16/0x20
Jun 27 20:07:45 ******\* kernel: [<ffffffff81614de9>] system_call_fastpath+0x16/0x1b
Jun 27 20:08:44 ******\* kernel: ata1.00: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x6 frozen
Jun 27 20:08:44 ******\* kernel: ata1.00: failed command: FLUSH CACHE EXT
Jun 27 20:08:44 ******\* kernel: ata1.00: cmd ea/00:00:00:00:00/00:00:00:00:00/a0 tag 22
         res 40/00:00:00:00:00/00:00:00:00:00/00 Emask 0x4 (timeout)
Jun 27 20:08:44 ******\* kernel: ata1.00: status: { DRDY }
Jun 27 20:08:44 ******\* kernel: ata1: hard resetting link
Jun 27 20:08:50 ******\* kernel: ata1: link is slow to respond, please be patient (ready=0)
Jun 27 20:08:52 ******\* kernel: ata1: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Jun 27 20:08:53 ******\* kernel: ata1.00: configured for UDMA/133
Jun 27 20:08:53 ******\* kernel: ata1.00: retrying FLUSH 0xea Emask 0x4
Jun 27 20:08:53 ******\* kernel: ata1.00: device reported invalid CHS sector 0
Jun 27 20:08:53 ******\* kernel: ata1: EH complete

**Comment by LordRalex** [comment]
You have a hard drive that is failing.
