### ISSUE TITLE
Path of the logfile

### ISSUE THREAD

**Issue by ghost** [PufferPanel/Scales#3]
Hello,

i was asked to make an issue here. 
By now PufferPanel picks the logfile from /logs/latest.log where it is stored in the newer versions of minecraft. But if you are using a older version like 1.4.7 or 1.5.2 the logfile is stored at /server.log and because of that the console cant't find a file at /logs/latest.log and the console shows:
"No log was found to read from. [/logs/latest.log]"

A option to set where the logfile is located would be great so.

Kind regards,
Cometex

**Comment by DaneEveritt** [comment]
This is something that is handled outside of PufferPanel, no way to handle that from the panel itself. Rather, the plugin files for Minecraft and other games specify where log files can be found. For this issue all we need to do is make another plugin file for older versions of Minecraft, easy thing to do.

**Comment by DaneEveritt** [comment]
Fixed this issue. :)
