### ISSUE TITLE
Installer process fails after downloading jar

### ISSUE THREAD

**Issue by idkw** [PufferPanel/Scales#30]
I have added a remote node on my puffer panel. he node shows greens in the server list.
When I try to add a server on that node, it starts the download process an effectively create the server directory on the remote computer.

However after downloading the minecraft jar it exits the process and the install is not finished.

```
Downloading Remote File...
https://s3.amazonaws.com/Minecraft.Download/versions/1.8.4/minecraft_server.1.8.4.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 9550k    1  118k    0     0   108k      0  0:01:27  0:00:01  0:01:26  136k
 60 9550k   60 5817k    0     0  2789k      0  0:00:03  0:00:02  0:00:01 3112k
100 9550k  100 9550k    0     0  3807k      0  0:00:02  0:00:02 --:--:-- 4170k
Fixing permissions for downloaded files...
Exiting Installer
```

Then in `Control Server` I see : 

```
Error: Service Temporarily Unavaliable
The requested server is still completing the install process. Please check back in a few minutes, you should recieve an email as soon as this process is completed.
```

And in the DB the field `installed` of that server stays at `0`.

I then have to manually set `installed` to `1` in the DB and I can finally control the server from the panel, which is rather annoying to do that for every server.

What could possibly had gone wrong ?

**Comment by DaneEveritt** [comment]
It sounds like there is a communication issue between the Scales daemon and PufferPanel since the installer is running correctly. Check your Scales and PufferPanel core logs to see if there is any error recorded.

**Comment by idkw** [comment]
Indeed, I've found this statement in the logs of scales deamon on the remote node :  
`01:33:56 - error: Failed to alert PufferPanel of completed install status. [PufferPanel said: undefined] code=ETIMEDOUT, errno=ETIMEDOUT, syscall=connect`

I guess that my iptables rules has forbidden the remote node to contact the server running the panel. However I have accepted on the panel server all incoming requests to the destination port 443 (HTTPS).

I have a self signed certificates on both nodes. Can it be the source of the bug ?

Can you tell me where are the logs of the panel, I can't find them and the documentation doesn't mention anything about such logs.

**Comment by DaneEveritt** [comment]
It looks like the connection is timing out, not that the connection is being refused by something.

`code=ETIMEDOUT`

The logs for PufferPanel can be found in `src/logs`

**Comment by idkw** [comment]
Nothing more shows up in the panel logs.

**Comment by idkw** [comment]
I've found this issue on which you have commented.
https://community.pufferpanel.com/topic/11-failed-to-alert-pufferpanel/
I may have the same issue because I remember having set some certificate fields blanks like email, ...
I'll try to regenerate the certificate with not empty fields.
Anyway this is a scales bug because in my browser I can accept such a certificate with blank fields with no errors.

**Comment by idkw** [comment]
I have created 3 new certificates on the two scales instances and on the panel with no blank fields but it still fails to finish the install process. 
Disabling the firewalls on both nodes doesn't change the issue.
What else could possibly cause this timeout issue ? Are you able to reproduce this ?

**Comment by idkw** [comment]
I have solved my issue. It was a config error.
The config.json the panel gave me had the urls written with http.
I manually changed them to https and it works now.

```
 "urls": {
                "repo": "https://xxxxxxxxxxxxx.fr/auth/remote/pack",
                "download": "https://xxxxxxxxxxx.fr/auth/remote/download",
                "install": "https://xxxxxxxxxxxxx.fr/auth/remote/install-progress"
        },

```

You may write some warning in the panel to tell the user to choose http or https when generating the default config.json file.

**Comment by DaneEveritt** [comment]
Good to know, I will add a note to add that when changing the HTTPS config. Currently it shows with `http/s` but only after you make a change, so if you add the config and then change it, it doesn't update.
