### ISSUE TITLE
Seperate the server plugins from Scales core

### ISSUE THREAD

**Issue by onbjerg** [PufferPanel/Scales#32]
We should probably have the server plugins such as Minecraft and SRCDS seperate from Scales itself. This will allow other users to create their own server plugins in a more easy manner. It will also streamline the contributions and seperate the issues from Scales core and the specific server plugins.

Looking at the code right now, this shouldn't be too hard.

Maybe we could even make a sort of marketplace to install the plugins with a single click, much akin the plugin manager in Atom.

It will also further reduce bloat when we add more games to Scales.

**Comment by LordRalex** [comment]
This is already something I planned on addressing. Scales as a whole to me is inefficient, and that is just one bit I want to deal with.
