### ISSUE TITLE
Player count is wrong

### ISSUE THREAD

**Issue by Malachiel87** [PufferPanel/Scales#34]
I just noticed the player count on server statistics is messed: it say
Players Online
andaroma2009crepperboy999rado2003MotorGAM3X

Instead on /list command
[12:12:20 INFO]: pecora, XpinguX, Tania, kratos007, IL_MASTINO, ChipsterMC, DasBananaHD, Pedrobra, emasale1234, ShishPvp_, xgeymer007, MissTiger_, masterj, tanker6211, puddypvp, dragone007, Wam1211, cobra2002, TheStalker, xT_Files, magnitude, andrea002, TheGoodPlayer, Dalex009, saverio23, partypankes, MeMeField, RazzMann, Ultron

Also i would suggest instead to show all player name, show the number of players that are playing on that server

**Comment by DaneEveritt** [comment]
Did it stay like that or eventually update?

**Comment by Malachiel87** [comment]
it stay like that... is a server connected to bungeecord server

**Comment by jaredtbates** [comment]
Yes, this happens to me as well... I'm not sure exactly why or what exactly though.

**Comment by DaneEveritt** [comment]
Can you confirm if this is simply a display issue in the panel or if it is an issue with Scales collection information? I.e. is Scales reporting the wrong information, or is the panel simply displaying the information wrong.

**Comment by Malachiel87** [comment]
how i can check if is a issue of scales or pufferpanel?

**Comment by DaneEveritt** [comment]
Wait, so @ET-Bent said in PufferPanel/PufferPanel#477 that this is showing players from the wrong server, which appears to be happening to you as well? This is very much not standard behavior and should not be happening. Is this only happening with BungeeCord servers or with any server?

**Comment by bentalexanderhaase** [comment]
For us this happens on standard Forge & Minecraft Vanilla servers. No Bungee cord in use. Seems to be the case if you use an upgraded version of Pufferpanel. On a new setup everything works fine.

**Comment by Malachiel87** [comment]
I just used the standard installation guide, i didn't any strange thing here
