### ISSUE TITLE
Scales FreeBSD support

### ISSUE THREAD

**Issue by ihatemyisp** [PufferPanel/Scales#37]
So I'm working to try and get Scales working on FreeBSD, but I've hit a road block in my testing. I've edited to user creation script to utilized pw but I get the following error in the logs:

> 20:43:51 - error: Error occured trying to execute a command to add a user. meta=./lib/scripts/create_user.sh: not found

I've gone so far as to hardcode the script path into the process.js and it still fails.

**Comment by ihatemyisp** [comment]
I've modified the create_user, minecraft_install, and remove_user bash scripts to support FreeBSD.
The shebang has been changed on all to reflect a port install of Bash:

``` bash
#!/usr/local/bin/bash
```

The user creation script has been changed to support account generation with pw:

``` bash
(comment out the useradd and usermod commands with a #)
pw useradd $2 -m -d $1$2 -p $(openssl passwd -1 $3) $2 -G scaleuser
```

Note that I haven't tested the remove_user script, nor the non-vanilla minecraft install. I'm sure there are changes to be made to get them working.

I'll also note that I'm sure a conditional statement in process.js could be made to fire off a separate script based off the output of `uname -s`

**Comment by puffrfish** [comment]
Thanks for looking into this. Unfortunately, Scales v0.2.0 won't be able to support FreeBSD right now, but I'd really like it to in future versions. For reference, this issue was regarding version v0.1.5 of Scales which is compatible with v0.8.2 of PufferPanel.
