### ISSUE TITLE
Block server start while chown

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/Scales#38]
While the panel is chowning the files of the server to start it should be forbidden to press the start button because if you press it it starts a second chown process. This is especially a problem when a user of the panel is not aware of the chown process that of course can take a while if the server is very big.

**Comment by DaneEveritt** [comment]
The actual server start is blocked, appears that we need to set the status before crowning to disable that button though. Pressing start should only start the sever once though, even if you press it multiple times.

**Comment by Paktosan** [comment]
Yeah but the problem is that if you have more chown processes than necessary which can take quite a long time on a traditional hard drive when the server is big they are slowing down other services which have to write to the hard drive.
