### ISSUE TITLE
Servers unable to connect to local ports

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/Scales#49]
Servers running inside containers are unable to connect to the host machine's local ports (example: MySQL 127.0.0.1:3306). Servers are able to connect using the external IP, but this is not ideal for many situations.

**Comment by bentalexanderhaase** [comment]
We had the same issue and are currently investigating in possible solutions. The only working solution for now is using an external server that runs our databases. 

What might work is making your desired database available from any host and using the external ip of your server. For this you also need to bind your MySQL server to your external ip in the my.cnf (see `locate my.cnf` to find the file, in most distributions it's found here `/etc/mysql/my.cnf`).

**Comment by DaneEveritt** [comment]
@ET-Bent — @LordRalex actually brought up a really easy solution for this: bind MySQL to your `docker0` interface. If you run `ifconfig docker0` you should be able to get the info you need.

```
dane@ubuntu:~$ ifconfig docker0
docker0   Link encap:Ethernet  HWaddr 02:42:62:a2:37:f1  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

In this case I would bind MySQL to `172.17.42.1`. Should make it accessible from containers.

**Comment by bentalexanderhaase** [comment]
@DaneEveritt thanks, of course I tried that but unfortunately this did not help with MySQL either, the only way is to go "out of the server" to it's external ip and then back in. Docker seems to isolate a container from the host and even the bridge docker0 cannot connect to the localhost/127.0.0.1

**Comment by LordRalex** [comment]
@ET-Bent why are you connecting to localhost/127.0.0.1?

Host binds to 172.17.42.1, and any container that needs to access the db uses 172.17.42.1 to connect.  The host will also connect to 172.17.42.1. The NIC is still local to the machine, and so nothing external can reach it, but now all containers can reach it.

**Comment by bentalexanderhaase** [comment]
@LordRalex I was testing binding to 172.17.42.1 which in my understanding is a bridge to the server nic. So any connection going to 172.17.42.1 should be handled the same as "localhost" but it is unfortunately not. After some testing the only thing working is using the external ip.

**Comment by LordRalex** [comment]
localhost != 172.17.42.1.

If you have MySQL bound to 172.17.42.1, you need to connect to that. Using localhost may work on some apps, but not always. MySQL I believe does not work like that.

**Comment by jaredtbates** [comment]
On Linux localhost defaults to 127.0.0.1. This can be changed, however, in `/etc/hosts`.

**Comment by LordRalex** [comment]
There is 0 reason to change that though, considering in a lot of cases, it's done using the loopback interface.
