### ISSUE TITLE
Possibility to forward more ports than just the one of the gameserver

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/Scales#50]
So on one of my minecraft servers i am running a dynmap that is no longer working because the port of it is not forwarded from the docker container. Is it possible to implement a option to define more ports to forward from the docker container?

**Comment by DaneEveritt** [comment]
It is on the roadmap for future versions. Scales v0.2 doesn't handle this since it would require changes to PufferPanel which we were trying to avoid since we are working on v0.9. Once PufferPanel v0.9 is out expect to see that functionality in there.

**Comment by bentalexanderhaase** [comment]
Yes wanted to post the same issue. Is it possible to manually edit the startup parameters for the docker proxy? If so it would be a nice work-around. I really appreciate the use of docker though!

**Comment by DaneEveritt** [comment]
This is something I am currently working on getting implemented as a quick release for you guys. It won't be supported by default within PufferPanel (at least not until `0.9`), but you will be able to edit the configuration file to get it working. I'll add instructions once I add it. Sorry for the troubles!

**Comment by bentalexanderhaase** [comment]
Thanks Dane really appreciated!

**Comment by DaneEveritt** [comment]
Alright, just pushed support for this in 8ac9897, so give me a minute to push the release and you can update to `0.2.1` and get support for it.

To use it, you will need to manually edit the servers config file in `data/uuid.json` and add a `mapping` key to the build object.

In the example below if your program in the container is listening on `25565` then it is accessible to the rest of the internet by `192.168.0.8:25566`, and the port `25580` in the container is accessible by `192.168.0.8:3309`. This opens up both `tcp` and `udp` as well.

```
"build": {
    "mapping": {
        "192.168.0.8": {
            "25565": "25566",
            "25580": "3309"
        },
        "ip_address": {
            "internal": "external"
        }
    },
    . . .
}
```

After doing that, you will need to change something in PufferPanel for the server (e.g. disk space) to have the container rebuilt. After it is rebuilt those ports will be accessible.

You may also make a cURL call to the `/server/rebuild-container` endpoint to have it rebuild.

**Comment by bentalexanderhaase** [comment]
Perfect! I will give you feedback tomorrow, need to get some sleep now, really happy you implemented this so quick! Looking forward to Pufferpanel. Btw. does disk space limiting now work with the containers, before docker I somewhere read in the forums this property has not been used? I think RAM and CPU allocation works as it should so every container has those resources assigned?

**Comment by DaneEveritt** [comment]
Nope, still doesn't work unfortunately. Working on some solutions for that, but it isn't as simple with docker.

**Comment by bentalexanderhaase** [comment]
Upon sending a request to the nodes API enpoint I get this error:

`{"code":"MethodNotAllowedError","message":"GET is not allowed"}`

Command:

```
curl -X "GET" "https://pufferpanel.ourserver.com:5656/server/rebuild-container" \
  -H "X-Access-Server: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" \
  -H "X-Access-Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

Using the `hash` value as `X-Access-Server` and `daemon_secret` as `X-Access-Token` (both taken from the database). 

In general the connection seems to work when using just `... "https://pufferpanel.ourserver.com:5656/server/" ...` I successfully receive all server parameters.

Unfortunately changing something in the web-panel overwrites all changes manually made in the config file. The diskspace is not changeable from the web-panel either because the text field is disabled once set.

**Comment by DaneEveritt** [comment]
Are you on Scales 0.2.1? Also disk space is not fully implemented anyways.

**Comment by bentalexanderhaase** [comment]
Yes scales 0.2.1

**Comment by DaneEveritt** [comment]
Are you 100% sure its 0.2.1 and not 0.2.2? 0.2.1 uses a GET request to that endpoint, 0.2.2 uses a PUT request. Try using PUT not GET and see if it works.

**Comment by bentalexanderhaase** [comment]
Will see! Thanks!

**Comment by bentalexanderhaase** [comment]
Same script as mentioned before, using `curl -X "PUT"  ...` --> `{"code":"MethodNotAllowedError","message":"PUT is not allowed"}`

Current local repositories head points to `c1b0c653eef1fb331fca25edf9684af4d64914c5`. Which is version 0.2.1 --> https://github.com/PufferPanel/Scales/commit/c1b0c653eef1fb331fca25edf9684af4d64914c5

Tell me any output you need.

**Comment by DaneEveritt** [comment]
You're on `0.2.0` the head for `0.2.1` is 8ac9897

**Comment by bentalexanderhaase** [comment]
okay my bad, will update as soon as not that many people are online, thanks!

**Comment by bentalexanderhaase** [comment]
Okay after updating (https://community.pufferpanel.com/topic/222-scales-v021-release/) I got the following error using the same script above (with "GET") that works without any problem getting the server parameters but fails upon rebuilding with this --> `{"message":"You do not have permission to perform that action."}`

**Comment by DaneEveritt** [comment]
You need to use a global token, not a per server one. Use the key from your config.json or just press the update server button in the admin CP when viewing a server.
