### ISSUE TITLE
FAILED TO BIND TO PORT after upgrade to Scales 0.2.0

### ISSUE THREAD

**Issue by bentalexanderhaase** [PufferPanel/Scales#52]
When starting a Minecraft server with Scales after upgrading from 0.1.4 to 0.2.0 you get the following error and the server crashes:

```
Starting Minecraft server on SOMEIP:25565
**** FAILED TO BIND TO PORT!
The exception was: java.net.BindException: Cannot assign requested address
Perhaps a server is already running on that port?
```

This happens due to the fact that previous Scales / Pufferpanel versions were replacing the server ip string in the server.properties with the Linux servers ip address before e.g. `server-ip=SOMEIP`

Because servers now start in docker, the local server ip is unknown / unreachable for the java process. To fix the problem you need to remove the ip from `server-ip=127.0.0.1` so the property is empty `server-ip=`

After this process everything works fine again. Is it possible to automate this process again like before but now rather than adding the ip simply checking if the property is empty and if not removing it?

**Comment by DaneEveritt** [comment]
That is something that is noted in the upgrade documentation, and there isn't really a clean way to do this, unless the upgrade script went through and checked everything for the user. There is the potential for use cases down the road where having a `server-ip` set could be useful, so I don't want to be changing it to something else or removing it each time.
