### ISSUE TITLE
start docker container failed: cpu.cfs_quota_us: permission denied - linked issue #17587

### ISSUE THREAD

**Issue by mapl** [PufferPanel/Scales#56]
https://github.com/docker/docker/issues/17587

**Comment by DaneEveritt** [comment]
What hosting provider are you using? You're using an unreleased version of Scales, so you probably didn't see the documentation page about users running on OVH systems who need to reinstall a non-OVH kernel.

**Comment by mapl** [comment]
I am using ngz.net 

-"docker run hello-world" itself ran without any issues

The Kernel ist standard too:

uname -r
3.16.0-4-amd64

As far is remember I've simply used http://scales.pufferpanel.com/docs (0.2.1)

**Comment by DaneEveritt** [comment]
The last time I saw this issue occurring it was because of a kernel issue. 0.2.2 also runs totally fine on other systems I've installed and tested it on, so it is a hard thing to track down.

**Comment by mapl** [comment]
I guess so too, that's why opened an issue for docker. for some reason the cpu.cfs_quota_us feature is missing in the kernel or a defect somehow. 
Can you lead me to the kernel issue youve encountered with the error? maybe its helpful

**Comment by DaneEveritt** [comment]
[This is the documentation](http://scales.pufferpanel.com/v0.2.2/docs/switching-ovh-kernels) for switching kernels on OVH, and it might be worth trying on your system, not sure if they are using a custom kernel.

Basically:

> The dedicated servers at OVH come with their own custom kernel. The kernel is compiled without support for modules, so virtualization solutions like KVM / libvirt / Xen will show error messages and refuse to work.

**Comment by mapl** [comment]
I have updated the issue on docker
docker/docker#17587

**Comment by mapl** [comment]
please close. recompiled kernel did the trick with cfs bandwidth
