### ISSUE TITLE
Add template support for SRCDS dedicated Gameservers 

### ISSUE THREAD

**Issue by mapl** [PufferPanel/Scales#59]
Please add template support for SRCDS dedidcated Gameservers 

eg. Team Fortress 2 dedidicated Linux Server:
SRCDS Application ID ${build_params} : 232250 
SRCDS Game ${game}: tf

**Comment by DaneEveritt** [comment]
Please use the forums for feature requests, thanks! :)

**Comment by DaneEveritt** [comment]
I lied, you can use Github for this.

**Comment by mapl** [comment]
:) I wanted to set the enhancement label on this, but it seems I don't have the sufficient permission
