### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by ghost** [PufferPanel/Scales#6]
Where is the example config.json?

**Comment by LordRalex** [comment]
The example config is provided from the panel. It is not provided through Scales itself.

**Comment by ghost** [comment]
The config from the panel is not working

**Comment by LordRalex** [comment]
Well, considering 
a) Scales is not released yet for the panel
b) The panel version that uses Scales is not out

That is not surprising at all.

**Comment by ghost** [comment]
Okay thanks.
