### ISSUE TITLE
Enhancement request: check docker config prior docker container creation for possible issues

### ISSUE THREAD

**Issue by mapl** [PufferPanel/Scales#60]
by using the builtin docker script you can check the current docker config for needed features like CFS which are required for a successful deployment.

This will check all kernel features and more.

/usr/share/docker-engine/contrib/check-config.sh

**Comment by DaneEveritt** [comment]
That is part of our checking for debugging, [information here](http://scales.pufferpanel.com/docs/check-server-kernel) and it'd be great to enable it in our installer.

We're looking into it for sure, just need to figure out what things we absolutely need, and what things we don't. Additionally Docker `1.9` seems to be smart enough that it will disable flags if the kernel doesn't support it. For example, Debian 8.2 ignores the CPU and Memory limiting flags when making containers.
