### ISSUE TITLE
Docker problems

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/Scales#61]
So I upgraded my Scales to a version using docker. Unfornately I got the following error:
https://gist.github.com/Paktosan/c41ffd27631bbe8f16f4
I am running Debian 8 on my system. All packages claim to be up to date.

**Comment by DaneEveritt** [comment]
Please see [this reply](https://community.pufferpanel.com/topic/287-server-does-not-start-reboot-loop/#comment-1186) and see if that fixes your problem.

Debian is going down a strange path and causing problems with Docker for whatever reason.

**Comment by Paktosan** [comment]
Awesome, that works, thanks!
