### ISSUE TITLE
Add option to start servers upon start of Scales

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/Scales#62]
An option when starting scales to start all of the containers that Scales manages would be very useful to people trying to have their servers start on reboot.

**Comment by DaneEveritt** [comment]
Would be fairly trivial to implement, just need to store the current server state in a file and then when Scales is shutdown simply don't update that file. On boot it would just run through the files and if their state was `on` just boot it up as we go.

Probably not going to add this as a minor point release, would be released in the next installment of Scales with PP `0.9.0`.
