### ISSUE TITLE
autodeploy script: scales does not fully initialize..

### ISSUE THREAD

**Issue by mapl** [PufferPanel/Scales#63]
OK
working scales installation:
[INFO] + ========================================== +
[INFO] | Scales logs all information, (inc. errors) |
[INFO] | into the logs/ directory. Please check     |
[INFO] | there before asking for help with bugs.    |
[INFO] |                                            |
[INFO] | Submit bug reports at the following link:  |
[INFO] | https://github.com/PufferPanel/Scales      |
[INFO] + ========================================== +
[VERBOSE] All scripts in /lib/scripts successfully had their permissions updated.
[INFO] Scales is now listening on port 5656
[VERBOSE] Loaded server configuration for xxxxxxxx-ccxxxxxc-9xx5-6c00xxxxxxf

BUT..

not working: 
new scales installation in another directory with auto deploy script (had to comment out add user to group stuff because I already have a working scales installation.. 
installtion was successful)
[INFO] + ========================================== +
[INFO] | Scales logs all information, (inc. errors) |
[INFO] | into the logs/ directory. Please check     |
[INFO] | there before asking for help with bugs.    |
[INFO] |                                            |
[INFO] | Submit bug reports at the following link:  |
[INFO] | https://github.com/PufferPanel/Scales      |
[INFO] + ========================================== +
[VERBOSE] All scripts in /lib/scripts successfully had their permissions updated.
[INFO] Scales is now listening on port 5656
<..nothing more.. no errors etc... I am missing >> Loaded server configuration<<<
but config.json is there and is identically to the working scales config.json.>

**Comment by DaneEveritt** [comment]
Im confused about what you are saying, and what you are even doing.

**Comment by mapl** [comment]
i tested out the autp deploy script which work quite well (when you ignore the scales user is already present or so..) in the end scales was running but.. for some reason is does not really load the json file.

**Comment by DaneEveritt** [comment]
It looks fine to me. It isn't going to say anything about loading `config.json`. It will display `Loaded server configuration` for each file in the `data/` folder that exists.

**Comment by mapl** [comment]
my fault yes, I checked the /data folder and it was empty. I copied the xxxxxxxxxxxxxxxxxxxx.json file the new scales installation and now it loads :) BIG SORRY :))

Perhaps you can adjust the auto deloy installation script to catch the ..((already present)) like errors which prevents a successful installation

Cheers
