### ISSUE TITLE
Issue when making a server

### ISSUE THREAD

**Issue by AntiEngineer** [PufferPanel/Scales#66]
Hi, I have a problem with Scales, my error is

An error occured while trying to connect to the remote node. Please check that Scales is running and try again.

When i try to stop and start Scales, it says this

stop.

 Command executed: /srv/scales: npm stop

Output: > Scales@0.2.3 stop /srv/scales

> forever stop index.js

error:   Forever cannot find process with id: index.js

npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "stop"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Scales@0.2.3 stop: `forever stop index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Scales@0.2.3 stop script 'forever stop index.js'.
npm ERR! This is most likely a problem with the Scales package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     forever stop index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Scales
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/scales/npm-debug.log

**Comment by puffrfish** [comment]
This is caused because when you run npm stop and Scales is not running, it gets upset. I believe we solved your issues on IRC so I am closing this issue. For further questions regarding usage please open up a thread on https://community.pufferpanel.com
