### ISSUE TITLE
Scales uses a whole core

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/Scales#68]
Hello,
we are running Scales 0.2.3 and having the issue that it consumes a whole core of the cpu. It is fixable by restarting Scales but the issue comes back after a while. There are no anomalys visible in the log.
![bildschirmfoto vom 2016-01-04 12-40-37](https://cloud.githubusercontent.com/assets/4009269/12089044/f4c4f79c-b2e0-11e5-8133-cee7ad9e5041.png)

**Comment by LordRalex** [comment]
Does this still occur?

**Comment by Paktosan** [comment]
Need to test it with the new scales version. Please give me some time.
