### ISSUE TITLE
Scales won't install anymore after 0.2.4

### ISSUE THREAD

**Issue by iaxedu** [PufferPanel/Scales#72]
npm-debug.log: http://pastebin.com/VYSYr5TG

And an additional screenshot: http://pastebin.com/VYSYr5TG

I've installed it now for like 10 times it always worked this is since 0.2.4

**Comment by LordRalex** [comment]
We did not test against Node 4.2.6, and in fact actually ship 4.2.4 with the current "bundle".
 I will see if it is an issue specific to 4.2.6, because that log suggests they have changed stuff.

**Comment by iaxedu** [comment]
I didn't link the screenshot properly it shows what is wrong: http://i.imgur.com/Ir5rRQL.png and http://i.imgur.com/0jN3BuS.png

They basically no longer allow a user with a Capital... Any idea how I could quickly fix this?

**Comment by LordRalex** [comment]
Your first error is because the "scales" file is not marked as executable
`chmod +x scales`

As for the second error, I will have to release a new version to fix that. In the meantime, you can edit the package.json file and lowercase the name value.

**Comment by LordRalex** [comment]
I am also curious, why are you using npm owner ls Scales? You don't have a reason to use it, nor is it how you start Scales.

**Comment by DaneEveritt** [comment]
The second error isn't an error. Scales just isn't distributed over npm because it doesn't need to be.

**Comment by iaxedu** [comment]
Just tried to find enough information in order for you  to find out what was wrong ^^ Your suggestion worked thanks!

**Comment by LordRalex** [comment]
Okay, cause you provided a lot more information than I needed, which threw me off. As part of the update and install scripts, it should have set the correct permissions on the executable to avoid that problem. Was this an 0.2.3 upgrade and what documentation did you follow?

**Comment by iaxedu** [comment]
I used the auto deploy script but it was PufferPanel 0.8.4 (Couldn't update but fixed that) New script works like a charm thanks for your help.
