### ISSUE TITLE
Permissions on files are not applied anymore on server start (scales 0.2.4 no docker)

### ISSUE THREAD

**Issue by Malachiel87** [PufferPanel/Scales#73]
Files are not setted with the correct permission of server anymore on scales 0.2.4

**Comment by LordRalex** [comment]
This was intentional, because there should not be a need for this, as the process is already running as the user the files should already be owned to. Not only is that expensive to do (get enough files and watch the time), it is redundant.

Do you get an error because of permissions? Why is this an issue?

**Comment by Malachiel87** [comment]
is a issue because i am uploading files with filezilla direct (as root) as i remember, when i start the server, all files that are dont have the correct permission (example files with root owner that i uploaded in pp-bedwar_hp5na/pubblic folder) are autoconverted magically in correct owner based of server (pp-bedwar_hp5na). This don't happen anymore with scales 0.2.4

**Comment by LordRalex** [comment]
Why are you uploading as root, and not as the user you should be using to transfer files?

**Comment by Malachiel87** [comment]
Because i have 50+ server and is more handly for me to use this, example with panel console i can't upload world file and manage zipes

**Comment by iaxedu** [comment]
Do:

chown -R bedwar_hp5na:bedwar_hp5na /home/bedwar_hp5na

This updates the permissions to your scales user.

**Comment by Malachiel87** [comment]
i know but before 0.2.4 scales do it automatic at server start

**Comment by LordRalex** [comment]
We removed that feature because it did not add value. If you are not using the user you should be using, then you should be fixing the permissions yourself.
