### ISSUE TITLE
Pocketmine install fails permission issue

### ISSUE THREAD

**Issue by airix1** [PufferPanel/Scales#74]
gpg fails during pocketmine server install since home directory permission is set to root.

```
..
installer:~$ ./installer.sh -v stable
gpg: fatal: can't create directory /home/pp-serverp_a2iai/.gnupg: Permission denied
secmem usage: 0/0 bytes in 0/0 blocks of pool 0/65536`
```

```
root@server:/home# ls -l
total 4
drwxr-xr-x  5 root root 4096 Jan 31 09:47 pp-serverp_a2iai
```

**Comment by LordRalex** [comment]
Can you provide the entire log?

**Comment by LordRalex** [comment]
Please also try the latest version of Scales (simply override your Scales install with https://github.com/PufferPanel/Scales/archive/0.2.4.2.tar.gz)

**Comment by airix1** [comment]
Yes, that fixed it.  It now installs and runs properly.  Thanks.
