### ISSUE TITLE
Container rebuild triggering error

### ISSUE THREAD

**Issue by karatemaccie** [PufferPanel/Scales#76]
After doing a container rebuild, I get the following error from both the GUI and when using CURL:

{"code":"InternalError","message":"self.emit is not a function"}

**Comment by karatemaccie** [comment]
It appears to do it's job, rebuilding the container, but it doesn't apply any changes in the data/uuid.json

**Comment by LordRalex** [comment]
Can you provide the scales logs with this

**Comment by karatemaccie** [comment]
The scales logs does not print any related to an error. Only the panel client and the API output the error.

**Comment by LordRalex** [comment]
This includes in any file in the logs folder? It should have logged it somewhere

**Comment by karatemaccie** [comment]
Exactly. The only place where I can find the error, is in an `alert()` when clicking the button.

**Comment by incrementing** [comment]
I'm also having the same issue, I've added port mapping to my .json file and upon rebuilding the container I get the same error as @karatemaccie reported (with no errors logged anywhere other than an `alert();`).

**Comment by Livan-pro** [comment]
I have this error too. How can I add port mapping?

**Comment by incrementing** [comment]
If you don't need it, you can disable docker. That will remove the need for port mapping.
