### ISSUE TITLE
git checkout tags not known to Git

### ISSUE THREAD

**Issue by Thunderbird2** [PufferPanel/Scales#8]
Hello when I issue the following:
git checkout tags/$(git describe --abbrev=0 --tags)

I get the following error:
fatal: No names found, cannot describe anything.
error: pathspec 'tags/' did not match any file(s) known to git.

**Comment by DaneEveritt** [comment]
Scales is not released, and it should not be used unless you are running an unreleased version of PufferPanel 0.8.0. If that is the case, you don't need to checkout a tag.
