### ISSUE TITLE
Thermos Support?

### ISSUE THREAD

**Issue by xaoseric** [PufferPanel/Scales#85]
Hi,
Is it possible to implement Thermos support? Also, how would I go about doing so? I have it somewhat implemented, would I just move the Thermos jar and libraries folders to the parent directory? Or is there a way to unzip files in the current working directory? 
http://tcpr.github.io/Thermos/install
https://github.com/KookykraftMC/Scales/blob/master/lib/scripts/install/minecraft.sh

**Comment by puffrfish** [comment]
When using the Minecraft plugin you should be able to replace the minecraft.jar with the Thermos jarfile.
